import voiture from "../assets/img/voiture.jpg";

const offerData = [
  {
    id: 0,
    img: voiture,
    make: "Renault",
    model: "Twizy E-tech",
    city: "Paris",
    autonomy: "60 miles",
    miles: "150 miles",
    year: "2019",
    seats: "2",
    available: "yes",
  },
  {
    id: 1,
    img: voiture,
    make: "Renault",
    model: "Twingo E-Tech",
    city: "Paris",
    autonomy: "118 miles",
    miles: "292",
    year: "2019",
    seats: "4",
    available: "yes",
  },
  {
    id: 2,
    img: voiture,
    make: "Renault",
    model: "Twingo E-Tech",
    city: "Paris",
    autonomy: "118 miles",
    miles: "292",
    year: "2019",
    seats: "4",
    available: "yes",
  },
  {
    id: 3,
    img: voiture,
    make: "Renault",
    model: "Zoe E-Tech",
    city: "Paris",
    autonomy: "234 miles",
    miles: "230",
    year: "2021",
    seats: "4",
    available: "yes",
  },
  {
    id: 4,
    img: voiture,
    make: "Renault",
    model: "Megane E-Tech",
    city: "Paris",
    autonomy: "60 miles",
    miles: "303",
    year: "2020",
    seats: "4",
    available: "yes",
  },
  {
    id: 5,
    img: voiture,
    make: "Tesla",
    model: "Model Y",
    city: "Paris",
    autonomy: "507 miles",
    miles: "426",
    year: "2020",
    seats: "4",
    available: "yes",
  },
  {
    id: 6,
    img: voiture,
    make: "Tesla",
    model: "Model X",
    city: "Paris",
    autonomy: "259 miles",
    miles: "517",
    year: "2021",
    seats: "4",
    available: "yes",
  },
  {
    id: 7,
    img: voiture,
    make: "Tesla",
    model: "Model 3",
    city: "Paris",
    autonomy: "254 miles",
    miles: "384",
    year: "2022",
    seats: "4",
    available: "yes",
  },
];

export default offerData;
